### ISSUE TITLE
Blocker Ineffective Against Latest Tumblr 6.3.0.05

### ISSUE THREAD

**Issue by aspensmonster** [apsun/TumblrAdAway#3]
On mobile presently. Can provide more detail later of necessary.

Adb output:

```
06-24 18:48:18.774 I/ActivityManager(852): START u0 {dat=package:com.crossbowffs.tumblradaway cmp=de.robv.android.xposed.installer/.DownloadDetailsActivity (has extras)} from uid 10074 on display 0
06-24 18:48:28.943 I/ActivityManager(852): START u0 {act=android.intent.action.VIEW dat=https://github.com/apsun/TumblrAdAway cmp=android/com.android.internal.app.ResolverActivity (has extras)} from uid 10074 on display 0
06-24 18:48:31.513 I/ActivityManager(852): START u0 {act=android.intent.action.VIEW dat=https://github.com/apsun/TumblrAdAway flg=0x3000000 cmp=org.mozilla.firefox/org.mozilla.gecko.tabqueue.TabQueueDispatcher (has extras)} from uid 10074 on display 0
06-24 18:48:31.907 I/ActivityManager(852): START u0 {act=android.intent.action.VIEW dat=https://github.com/apsun/TumblrAdAway flg=0x13000000 cmp=org.mozilla.firefox/org.mozilla.gecko.BrowserApp (has extras)} from uid 10150 on display 0
06-24 19:05:28.958 I/TumblrAdAway(15013): Tumblr AdAway initializing...
06-24 19:05:28.958 I/TumblrAdAway(15013): Phone manufacturer: htc
06-24 19:05:28.959 I/TumblrAdAway(15013): Phone model: m8
06-24 19:05:28.959 I/TumblrAdAway(15013): Android version: 5.1.1
06-24 19:05:28.959 I/TumblrAdAway(15013): Xposed bridge version: 85
06-24 19:05:29.027 I/TumblrAdAway(15013): Tumblr APK version: 6.3.0.05 (106030005)
06-24 19:05:29.027 I/TumblrAdAway(15013): Tumblr AdAway version: 1.5 (6)
06-24 19:05:29.085 E/TumblrAdAway(15013): Exception occurred while hooking methods
06-24 19:05:29.085 E/TumblrAdAway(15013): java.lang.IllegalArgumentException: Cannot hook interfaces: public abstract void com.tumblr.ui.widget.timelineadapter.TimelineAdapter.applyItems(java.util.List,boolean)
06-24 19:05:29.085 E/TumblrAdAway(15013):   at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:587)
06-24 19:05:29.085 E/TumblrAdAway(15013):   at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:178)
06-24 19:05:29.085 E/TumblrAdAway(15013):   at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:251)
06-24 19:05:29.085 E/TumblrAdAway(15013):   at com.crossbowffs.tumblradaway.Hook.handleLoadPackage(Hook.java:95)
06-24 19:05:29.085 E/TumblrAdAway(15013):   at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
06-24 19:05:29.085 E/TumblrAdAway(15013):   at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
06-24 19:05:29.085 E/TumblrAdAway(15013):   at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
06-24 19:05:29.085 E/TumblrAdAway(15013):   at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:193)
06-24 19:05:29.085 E/TumblrAdAway(15013):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:720)
06-24 19:05:29.085 E/TumblrAdAway(15013):   at android.app.ActivityThread.handleBindApplication(<Xposed>)
06-24 19:05:29.085 E/TumblrAdAway(15013):   at android.app.ActivityThread.access$1600(ActivityThread.java:154)
06-24 19:05:29.085 E/TumblrAdAway(15013):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
06-24 19:05:29.085 E/TumblrAdAway(15013):   at android.os.Handler.dispatchMessage(Handler.java:102)
06-24 19:05:29.085 E/TumblrAdAway(15013):   at android.os.Looper.loop(Looper.java:135)
06-24 19:05:29.085 E/TumblrAdAway(15013):   at android.app.ActivityThread.main(ActivityThread.java:5294)
06-24 19:05:29.085 E/TumblrAdAway(15013):   at java.lang.reflect.Method.invoke(Native Method)
06-24 19:05:29.085 E/TumblrAdAway(15013):   at java.lang.reflect.Method.invoke(Method.java:372)
06-24 19:05:29.085 E/TumblrAdAway(15013):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
06-24 19:05:29.085 E/TumblrAdAway(15013):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
06-24 19:05:29.085 E/TumblrAdAway(15013):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
06-24 19:05:29.085 E/Xposed  (15013):   at com.crossbowffs.tumblradaway.Hook.handleLoadPackage(Hook.java:95)
06-24 19:07:39.969 I/TumblrAdAway(15680): Tumblr AdAway initializing...
06-24 19:07:39.969 I/TumblrAdAway(15680): Phone manufacturer: htc
06-24 19:07:39.969 I/TumblrAdAway(15680): Phone model: m8
06-24 19:07:39.969 I/TumblrAdAway(15680): Android version: 5.1.1
06-24 19:07:39.969 I/TumblrAdAway(15680): Xposed bridge version: 85
06-24 19:07:39.994 I/TumblrAdAway(15680): Tumblr APK version: 6.3.0.05 (106030005)
06-24 19:07:39.994 I/TumblrAdAway(15680): Tumblr AdAway version: 1.5 (6)
06-24 19:07:39.998 E/TumblrAdAway(15680): Exception occurred while hooking methods
06-24 19:07:39.998 E/TumblrAdAway(15680): java.lang.IllegalArgumentException: Cannot hook interfaces: public abstract void com.tumblr.ui.widget.timelineadapter.TimelineAdapter.applyItems(java.util.List,boolean)
06-24 19:07:39.998 E/TumblrAdAway(15680):   at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:587)
06-24 19:07:39.998 E/TumblrAdAway(15680):   at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:178)
06-24 19:07:39.998 E/TumblrAdAway(15680):   at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:251)
06-24 19:07:39.998 E/TumblrAdAway(15680):   at com.crossbowffs.tumblradaway.Hook.handleLoadPackage(Hook.java:95)
06-24 19:07:39.998 E/TumblrAdAway(15680):   at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
06-24 19:07:39.998 E/TumblrAdAway(15680):   at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
06-24 19:07:39.998 E/TumblrAdAway(15680):   at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
06-24 19:07:39.998 E/TumblrAdAway(15680):   at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:193)
06-24 19:07:39.998 E/TumblrAdAway(15680):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:720)
06-24 19:07:39.998 E/TumblrAdAway(15680):   at android.app.ActivityThread.handleBindApplication(<Xposed>)
06-24 19:07:39.998 E/TumblrAdAway(15680):   at android.app.ActivityThread.access$1600(ActivityThread.java:154)
06-24 19:07:39.998 E/TumblrAdAway(15680):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
06-24 19:07:39.998 E/TumblrAdAway(15680):   at android.os.Handler.dispatchMessage(Handler.java:102)
06-24 19:07:39.998 E/TumblrAdAway(15680):   at android.os.Looper.loop(Looper.java:135)
06-24 19:07:39.998 E/TumblrAdAway(15680):   at android.app.ActivityThread.main(ActivityThread.java:5294)
06-24 19:07:39.998 E/TumblrAdAway(15680):   at java.lang.reflect.Method.invoke(Native Method)
06-24 19:07:39.998 E/TumblrAdAway(15680):   at java.lang.reflect.Method.invoke(Method.java:372)
06-24 19:07:39.998 E/TumblrAdAway(15680):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
06-24 19:07:39.998 E/TumblrAdAway(15680):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
06-24 19:07:39.998 E/TumblrAdAway(15680):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
06-24 19:07:39.998 E/Xposed  (15680):   at com.crossbowffs.tumblradaway.Hook.handleLoadPackage(Hook.java:95)
```

**Comment by apsun** [comment]
Yup, I'm aware of this, will update shortly. Thanks for the log.

**Comment by apsun** [comment]
Fixed in https://github.com/apsun/TumblrAdAway/commit/642bc4264884b40a20c2a4e923a122c07450a2dc.
