### ISSUE TITLE
Module not working since summer update

### ISSUE THREAD

**Issue by kyrasantae** [apsun/TumblrAdAway#6]
The module has not worked for me since shortly after the update in June. I disabled all of my other modules, rebooted, and then started up Tumblr. Here's the xposed log after that. I've also tried uninstalling, rebooting, and then reinstalling, but it still doesn't work.

> -----------------
> 11.11.2016 20.57.15 UTC
> Loading Xposed v54 (for Zygote)...
> Running ROM 'KOT49H.G800FXXU1AOG2' with fingerprint 'samsung/kminiltexx/kminilte:4.4.2/KOT49H/G800FXXU1AOG2:user/release-keys'
> Loading modules from /data/app/com.crossbowffs.tumblradaway-7.apk
>   Loading class com.crossbowffs.tumblradaway.Hook
> de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tumblr.ui.widget.timelineadapter.SimpleTimelineAdapter
> 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
> 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
> 	at com.crossbowffs.tumblradaway.Hook.handleLoadPackage(Hook.java:95)
> 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
> 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
> 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
> 	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
> 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
> 	at android.app.ActivityThread.handleBindApplication(Native Method)
> 	at android.app.ActivityThread.access$1600(ActivityThread.java:172)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
> 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	at android.os.Looper.loop(Looper.java:146)
> 	at android.app.ActivityThread.main(ActivityThread.java:5694)
> 	at java.lang.reflect.Method.invokeNative(Native Method)
> 	at java.lang.reflect.Method.invoke(Method.java:515)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
> 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
> 	at dalvik.system.NativeStart.main(Native Method)
> Caused by: java.lang.ClassNotFoundException: com.tumblr.ui.widget.timelineadapter.SimpleTimelineAdapter
> 	at java.lang.Class.classForName(Native Method)
> 	at java.lang.Class.forName(Class.java:251)
> 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
> 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
> 	... 19 more
> Caused by: java.lang.NoClassDefFoundError: com/tumblr/ui/widget/timelineadapter/SimpleTimelineAdapter
> 	... 23 more
> Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tumblr.ui.widget.timelineadapter.SimpleTimelineAdapter" on path: DexPathList[[zip file "/data/app/com.tumblr-31.apk"],nativeLibraryDirectories=[/data/app-lib/com.tumblr-31, /vendor/lib, /system/lib]]
> 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)  
> 	... 23 more

**Comment by apsun** [comment]
What's your Tumblr app version? I downloaded the latest one from APKMirror and there's no reason the module should be failing with the error you posted.

Note that only the latest Tumblr version is supported. If you're running an older version, either update Tumblr or downgrade the Xposed module.

**Comment by kyrasantae** [comment]
I keep my apps regularly updated, so I am currently using 7.3.0.43.

**Comment by apsun** [comment]
That's really weird. Can you upload your Tumblr APK?

**Comment by kyrasantae** [comment]
[Fresh off my device ;)](https://www.dropbox.com/s/3tf8b2c5ewvnbw5/com.tumblr-31.apk)

**Comment by apsun** [comment]
This is baffling; the module is failing because it can't find the `com.tumblr.ui.widget.timelineadapter.SimpleTimelineAdapter` class, but the decompiled APK shows that it exists.

Sorry, I have no clue on what could be going wrong (the only device I have access to at the moment doesn't have Xposed, so I can't debug it beyond looking at the APK file). I can only suggest reinstalling (uninstalling -> installing) the Tumblr app.

**Comment by kyrasantae** [comment]
> I can only suggest reinstalling (uninstalling -> installing) the Tumblr app.

Just tried this, with a reboot in between. Still no luck. Weird. :/
